repos:
  # Common hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
        files: (ops|backward|op_[a-z_]+)\.yaml$
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        name: Tabs remover (C++)
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx|xpu|kps)$
        args: [--whitespaces-count, '2']
      - id: remove-tabs
        name: Tabs remover (Python)
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
        args: [--whitespaces-count, '4']
  # For Python files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
      - id: ruff-format
  # For C++ files
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./tools/codestyle/clang_format.sh -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx|xpu|kps)$
  - repo: local
    hooks:
      - id: cpplint-cpp-source
        name: cpplint
        description: Check C++ code style using cpplint.py.
        entry: bash ./tools/codestyle/cpplint_pre_commit.sh
        language: system
        files: \.(cc|cxx|cpp|cu|h|hpp|hxx)$
        args:
          - --extensions=cc,cxx,cpp,cu,cuh,h,hpp,hxx,kps
          - --filter=-readability/fn_size,-build/include_what_you_use,-build/c++11,-whitespace/parens,-legal/copyright
          - --quiet
  # For CMake files
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
  - repo: https://github.com/PFCCLab/cmake-lint-paddle
    rev: v1.5.1
    hooks:
      - id: cmakelint
        args: [--config=./tools/codestyle/.cmakelintrc]
  # For YAML files
  - repo: https://github.com/PFCCLab/yamlfmt-pre-commit-mirror.git
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        files: |
          (?x)^(
            \.github/.+\.(yaml|yml)|
            \.pre-commit-config\.yaml|
            \.yamlfmt|
            sgconfig\.yml|
            ci/rules/.+\.yml|
            ci/rule-tests/.+\.yml
          )
